name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x test002/gradlew
    
    - name: Install Gradle temporarily to fix wrapper
      run: |
        wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
        unzip -q gradle-8.0-bin.zip
        export PATH=$PWD/gradle-8.0/bin:$PATH
        echo "PATH=$PWD/gradle-8.0/bin:$PATH" >> $GITHUB_ENV
    
    - name: Fix gradle wrapper
      working-directory: test002
      run: |
        if ! ./gradlew --version; then
          gradle wrapper --gradle-version=8.0
          chmod +x gradlew
        fi
    
    - name: Fix Material 3 theme compatibility
      working-directory: test002
      run: |
        # 备份原文件
        cp app/src/main/res/values/themes.xml app/src/main/res/values/themes.xml.backup
        # 修复Material 3兼容性问题
        sed -i 's/colorPrimaryVariant/colorPrimary/g' app/src/main/res/values/themes.xml
        sed -i 's/colorSecondaryVariant/colorTertiary/g' app/src/main/res/values/themes.xml
        sed -i 's/?attr\/colorPrimaryVariant/?attr\/colorPrimary/g' app/src/main/res/values/themes.xml
        echo "=== Modified themes.xml ==="
        cat app/src/main/res/values/themes.xml
    
    - name: Clean and Build
      working-directory: test002
      run: |
        ./gradlew clean --no-daemon
        ./gradlew assembleDebug --no-daemon
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: test002/app/build/outputs/apk/debug/app-debug.apk
